### ISSUE TITLE
NetBeans 12.5/12.6 missing ARM based binaries for MacOSX terminal support in NetBeans

### ISSUE THREAD

**Issue by tmulle** [apache/netbeans#3467]
### Apache NetBeans version

Latest release

### What happened

When using the “Open in Terminal” option I get nothing but a blank terminal window when running on an M1 Silicon Pro MacBook Pro using native ARM based JDK

After debugging the source code of Netbeans itself it comes down to a missing resource in the “_netbeans/ide/bin/nativeexecution/_“ folder for “_MacOSX-unknown_64/pty_”

This is because the host information cannot figure out the *CPUFAMILY* and is returning “*UNKNOWN*”

Things I tried:

1. Changed the “_netbeans/ide/bin/nativeexecution/hostinfo.sh_” file as follows:

Add another check for CPUFAMILY and return ARM:

```
CPUFAMILY=`(echo ${CPUTYPE} | egrep "^i|x86_64|athlon|Intel" >/dev/null && echo x86) || echo ${CPUTYPE}`
if [ "${CPUFAMILY}" = "sparc64" ]; then
   CPUFAMILY="sparc"
fi

# New check if ARM64 then return ARM so Java code will stop returning “UNKNOWN”
if [ "${CPUFAMILY}" = "arm64" ]; then
   CPUFAMILY="arm"
fi

```

2. I’m a Java developer and don’t usually compile C++ but going into the “_netbeans/ide/dlight.nativeexecution/tools_” directory and manually running the ‘_buildall.sh_” script compiles almost all the files needed.

➜  tools git:(master) ✗ chmod +x ./buildall.sh
➜  tools git:(master) ✗ . ./buildall.sh

```
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
rm -rf ../release/bin/nativeexecution/MacOSX-arm ../release/bin/nativeexecution/MacOSX-arm
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
gcc  -s -O2  -o ../release/bin/nativeexecution/MacOSX-arm/privp privp.c
ld: warning: option -s is obsolete and being ignored
gcc  -s -O2  -o ../release/bin/nativeexecution/MacOSX-arm/process_start process_start.c
ld: warning: option -s is obsolete and being ignored
gcc  -s -O2  -o ../release/bin/nativeexecution/MacOSX-arm/pty_open pty_open.c
ld: warning: option -s is obsolete and being ignored
gcc  -s -O2   -s  -o ../release/bin/nativeexecution/MacOSX-arm/sigqueue sigqueue.c
sigqueue.c:53:12: error: implicit declaration of function 'sigqueue' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return sigqueue(pid, signo, value);
           ^
1 error generated.
make: *** [sigqueue] Error 1
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/dist/MacOSX-arm
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/dist
rm -f .make.state*
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/dist/MacOSX-arm
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/env.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/src/env.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/error.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/src/error.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/loop.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/src/loop.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/options.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/src/options.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/pty_fork.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/src/pty_fork.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/pty.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/src/pty.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/util.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/src/util.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
--------------------------------------------------------------------------------
gcc  -s -O2   -s  -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/dist/MacOSX-arm/pty /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/env.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/error.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/loop.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/options.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/pty_fork.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/pty.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/build/MacOSX-arm/src/util.o
ld: warning: option -s is obsolete and being ignored
ld: warning: option -s is obsolete and being ignored
================================================================================
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/pty/dist/MacOSX-arm/pty

-rwxr-xr-x  1 tmulle  staff  53520 Jan 14 13:25
Mach-O 64-bit executable arm64
================================================================================
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
expr: syntax error
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build/MacOSX-arm /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/dist/MacOSX-arm
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/dist
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
expr: syntax error
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/dist/MacOSX-arm
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build/MacOSX-arm/src
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build/MacOSX-arm/src/linux
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build/MacOSX-arm/src/solaris
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build/MacOSX-arm/src/macosx
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build/MacOSX-arm/src/error.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/src/error.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build/MacOSX-arm/src/killall.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/src/killall.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/src/killall.c:187:13: warning: enumeration value 'S_SID' not handled in switch [-Wswitch]
    switch (scope) {
            ^
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/src/killall.c:187:13: note: add missing switch cases
    switch (scope) {
            ^
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/src/killall.c:199:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/src/killall.c:260:16: error: implicit declaration of function 'sigqueue' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        return sigqueue(params.id, params.sig, value);
               ^
2 warnings and 1 error generated.
make: *** [/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/killall/build/MacOSX-arm/src/killall.o] Error 1
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/build/MacOSX-arm /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/dist/MacOSX-arm
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/build
rm -f -r /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/dist
rm -f .make.state*
Platform: MacOSX-arm
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
Makefile:85: warning: overriding commands for target `/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/dist/MacOSX-arm'
Makefile:81: warning: ignoring old commands for target `/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/dist/MacOSX-arm'
make: Circular /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/dist/MacOSX-arm <- /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/dist/MacOSX-arm dependency dropped.
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/build/MacOSX-arm/src
gcc  -s -O2   -c -o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/build/MacOSX-arm/src/unbuffer.o /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/src/unbuffer.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
mkdir -p /Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/dist/MacOSX-arm
================================================================================
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools/unbuffer/dist/MacOSX-arm/

total 0
drwxr-xr-x  2 tmulle  staff  64 Jan 14 13:25 .
drwxr-xr-x  3 tmulle  staff  96 Jan 14 13:25 ..
directory
================================================================================
/Users/tmulle/Development/Projects/netbeans/ide/dlight.nativeexecution/tools
================================================
buildall:               directory
buildall/pty:           Mach-O 64-bit executable arm64
buildall/pty_open:      Mach-O 64-bit executable arm64
buildall/process_start: Mach-O 64-bit executable arm64
buildall/privp:         Mach-O 64-bit executable arm64

```

If I then make a directory called “_netbeans/ide/bin/nativeexecution/MacOSX-arm_64_” and copy the “_buildall/_“ output into that directory the terminal works and I they are running *natively* (Not Rosetta).

Again, this worked for me but obviously someone with more knowledge will know how to fix this.

And yes, I know that you need a M1 Silicon Mac to build the binaries :-(

### Quick Fix

I was able to fix it temporarily with these steps but they are not ideal:

1. Step (1) from above is required

2. Copying the contents of “_netbeans/ide/bin/nativeexecution/MacOSX-x86_64_” to “_netbeans/ide/bin/nativeexecution/MacOSX-arm_64_”

This works, however, any terminal window is now using *Rosetta* and _NOT native ARM_ code

 

### How to reproduce

Try to open a Terminal window in either NetBeans 12.5 or 12.6 running on a native ARM JDK and you'll get a blank terminal window.

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

MacOS M1 Max Pro Monterey

### JDK

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode) also happens with JDK11

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

As requested from the email, here is the output:

```
➜  ~ uname -p
arm
➜  ~ uname -n
mars.fios-router.home
➜  ~ uname -s
Darwin
➜  ~ uname -a
Darwin mars.fios-router.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
➜  ~ sysctl hw.cpu64bit_capable
hw.cpu64bit_capable: 1
➜  ~ hostinfo
Mach kernel version:
	 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
Kernel configured for up to 10 processors.
10 processors are physically available.
10 processors are logically available.
Processor type: arm64e (ARM64E)
Processors active: 0 1 2 3 4 5 6 7 8 9
Primary memory available: 32.00 gigabytes
Default processor set: 628 tasks, 2916 threads, 10 processors
Load average: 1.34, Mach factor: 8.64
```

Here is also "uname -m" on both my M1 Mac and Intel:

"uname -m" = arm64
"uname -m" = x86_64

Original Request Email:

Hi Tim,

Thanks for your report!

It seems we're not contemplating the new M1 Apple computers. Since not all of us have access to one of these, would you please add the following to this ticket?

a) The result of "uname -p" (this is what we call CPUTYPE in [1])
b) The result of "uname -n" (this is what we call HOSTNAME in [1])
c) The result of "uname -s" (this is what we call OS in [1]).
d) The result of "uname -a" (we use it elsewhere in [1]).
e) The result of "sysctl hw.cpu64bit_capable" (may require 'sudo', this is what we call BITNESS, I assume this is 64 bit).
f) The result of "hostinfo"

It would be great if we could compile "dlight.nativeexecution/tools" for the new M1 processors by running "build.sh" in [2] on one of these computers (I don't own one, though). This will probably require adding new #include's in different parts of the code. We'll talk to ASF Infra to see if we can have one of these to compile.

Thanks again,
Antonio

[1]
[https://github.com/apache/netbeans/blob/master/ide/dlight.nativeexecution/release/bin/nativeexecution/hostinfo.sh]

[2]
[https://github.com/apache/netbeans/tree/master/ide/dlight.nativeexecution/tools]

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by oyarzun** [comment]
@tmulle can you build and test the binaries on a M1 Mac? https://github.com/oyarzun/netbeans/commit/5523c7fc1ed6318446e16840918e75d019a4d42b

@vieiro FYI, we can cross compile the binaries on an Intel mac.

**Comment by tmulle** [comment]
@oyarzun I cloned your git REPO and ran "_ant -Dcluster.config=basic_" like I did during my testing and I don't see any arm binaries in the directory. I ran the netbeans build and the terminal was blank.

```
netbeans git:(master) git config --get remote.origin.url
https://github.com/oyarzun/netbeans.git

```

After the build finished:
```
netbeans git:(master) ls nbbuild/netbeans/ide/bin/nativeexecution/
Linux-sparc_64/  Linux-x86_64/    MacOSX-x86_64/   SunOS-x86/       Windows-x86/     dorun.sh*
Linux-x86/       MacOSX-x86/      SunOS-sparc_64/  SunOS-x86_64/    Windows-x86_64/  hostinfo.sh
```

**Comment by tmulle** [comment]
Sorry..my bad. I didn't checkout the `macOS_arm` branch after pulling the code. But even after switching to the macOS_arm branch and building, the binaries are still not being generated.

Unless, I'm doing something wrong..

**Comment by oyarzun** [comment]
@tmulle the binaries are not built using ant. I believe ant will download precompiled binaries from http://netbeans.osuosl.org/binaries/06D8BC67B2F104F2DE773CB0F77AACE6B3DF553D-exechlp-1.0.zip
Assuming my changes works, a [PMC member would need to upload a new zip that includes the macOS arm binaries][1]. 

To test my branch you would need to run `sh ./buildall.sh` in the tools dir and manually copy the exes to `nbbuild/netbeans/ide/bin/nativeexecution/MacOS-arm`

FYI, I just pushed another commit to that branch since there was a typo in one of the makefiles.

[1]: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=115507251

**Comment by vieiro** [comment]
Hi @tmulle, as @oyarzun says it's just the `sh ./buildall.sh` that is required, i.e., you don't need to build the whole NetBeans. 

The steps to verify that the library can be built in M1 would be:

```sh
cd a-working-directory-you-want
git clone https://github.com/oyarzun/netbeans.git
cd netbeans
git checkout macos_arm
git pull # make sure we're in the last commit in this branch
cd ide/dlight.nativeexecution/tools/
sh ./buildall.sh
ls -ali ../release/bin/nativeexecution
```

**Comment by tmulle** [comment]
@oyarzun ok, that might have worked! 

Just a small change:

1. I had to copy the files built to **MacOSX_arm-64** and not **MacOSX-arm**. 


The _org.netbeans.modules.nativeexecution.api.util.HelperUtility.java_ class builds the file it's looking for as '_MacOSX_cpufamily_bitness_'

Here is where the **path** is used in that class..path is set to "_bin/nativeexecution/MacOSX-arm_64/pty_"
Using the original **MacOS-arm** as you mentioned causes a "_MissingResourceException_"

 ```
protected File getLocalFile(final ExecutionEnvironment env)
            throws ParseException, MissingResourceException {

        InstalledFileLocator fl = InstalledFileLocatorProvider.getDefault();
        MacroExpander expander = MacroExpanderFactory.getExpander(env);
        String path = expander.expandPredefinedMacros(pattern);

        File file = fl.locate(path, codeNameBase, false);

        if (file == null || !file.exists()) {
            throw new MissingResourceException(path, null, null); //NOI18N
        }

        return file;
    }
```

Once I had the correct directory, I then could open the terminal and according to Activity Monitor the PTY process was Apple instead of Intel which means it worked.

<img width="1456" alt="Screen Shot 2022-01-17 at 11 08 04 PM" src="https://user-images.githubusercontent.com/5183186/149869833-f0dc3ee2-cf3c-422d-9944-1a28db67ca5a.png">

**Comment by vieiro** [comment]
Hi @tmulle , thanks!

Would you please run this as well so we understand what exact files are generated?

```sh
cd a-working-directory-you-want # same places as above
cd netbeans
cd ide/dlight.nativeexecution/tools/
find ../release/bin/nativeexecution
```

i.e., we want to know the _exact_ names (i.e., if we're getting `MacOSX_arm-64`  or `MacOSX_arm_64`

You may want to zip that directory and attach here. 

@oyarzun , we'll need at least another independent compilation (to ensure @tmulle is not adding an extra bitcoin miner to the binaries :-D ) and then upload the zip and new hash with these.

**Comment by tmulle** [comment]
@vieiro haha..no bitminer code here :)

Here is the output of the find command.. I ran it inside the current macos_arm branch I previously built.

The NetBeans code wants the directory to be called '_MacOSX-arm_64_'

You can see it's building to the wrong directory name that the code is looking for as mentioned in my previous comment a few mins ago.

```
➜  netbeans git:(macos_arm) cd ide/dlight.nativeexecution/tools
➜  tools git:(macos_arm) find ../release/bin/nativeexecution
../release/bin/nativeexecution
../release/bin/nativeexecution/MacOSX-arm
../release/bin/nativeexecution/MacOSX-arm/pty_open
../release/bin/nativeexecution/MacOSX-arm/process_start
../release/bin/nativeexecution/MacOSX-arm/privp
../release/bin/nativeexecution/hostinfo.sh
../release/bin/nativeexecution/dorun.sh
```

**Comment by vieiro** [comment]
Thanks @tmulle ! Well, it's a pity we don't have a bitcoin miner in NetBeans :-D.

@oyarzun even though the binaries are added to the zip file, we still will need to modify the nbproject/project.properties file [1] so NetBeans adds them to the module (you can do that in `Properties/Libraries/Jar files` as well).


[1]
https://github.com/oyarzun/netbeans/blob/b693623ebc0cf40f16fc45015cc8eef73ec86e7e/ide/dlight.nativeexecution/nbproject/project.properties#L76

**Comment by neilcsmith-net** [comment]
Remove needs:triage - think we're sure this is a bug - @vieiro @oyarzun please remove that label on responding to an issue.

Also added needs:discussion as something to follow up on dev@ here - we should move the location of the binaries to Maven if possible, similar to the Windows launcher, and wind down usage of OSUOSL - cc @ebarboni and https://lists.apache.org/thread/9tf28w5r3wxx9fwbl12m6x36sb3pfdry

@oyarzun Swift launcher also going to be related to this?

For NB13 I wonder whether we should make the quick fix change at least, if we can't get this in?

**Comment by tmulle** [comment]
@vieiro @oyarzun Did you see the issue about possible resource leak above comment? in https://github.com/apache/netbeans/issues/3467#issuecomment-1015057137

Just want to make sure it's not missed in case it is a real issue..

**Comment by vieiro** [comment]
@neilcsmith-net , let's move this to the mailing list then.
@tmulle , it seems we have a "killall" utility in-there, maybe it's not working on M1. Needs some research :-).

**Comment by oyarzun** [comment]
> Remove needs:triage - think we're sure this is a bug - @vieiro @oyarzun please remove that label on responding to an issue.

I would say this is a feature rather than a bug as it is a new unsupported architecture. While we are adding this, we probably should add Linux arm as there are no binaries either.

> For NB13 I wonder whether we should make the quick fix change at least, if we can't get this in?

IMHO, these changes can wait until after NB13.

> Swift launcher also going to be related to this?

I looked at this as well, for the launcher we can create a universal binary that contains both the x86-64 and arm-64. Currently the NetBeans launcher is built when the macOS installer is created. @mcdonnell-john has been building these on his Mac. It can be created with the following command with the latest Swift 5.4 tools, and maybe 5.3.

```shell
swift build --configuration release --arch arm64 --arch x86_64
```

> Did you see the issue about possible resource leak above comment? in #3467 (comment)

@tmulle I just pushed a commit which should fix building the `killall` macOS arm binary.

> Also added needs:discussion as something to follow up on dev@ here - we should move the location of the binaries to Maven if possible, similar to the Windows launcher, and wind down usage of OSUOSL https://lists.apache.org/thread/9tf28w5r3wxx9fwbl12m6x36sb3pfdry

There are a few platform specific binaries that would benefit from moving the compilation and packaging to a better process. I will start a discussion thread on the dev mailing list.

**Comment by neilcsmith-net** [comment]
Just to add, I noticed this also fails when running with an x86_64 JDK on Apple Silicon.

**Comment by oyarzun** [comment]
I think the JDK is irrelevant since it uses the `hostinfo.sh` shell script to determine the underlying system info. Which once fixed to support arm would still return arm when running a x86_64 JDK.

https://github.com/apache/netbeans/blob/c084119009d2e0f736f225d706bc1827af283501/ide/dlight.nativeexecution/release/bin/nativeexecution/hostinfo.sh

https://github.com/apache/netbeans/blob/c084119009d2e0f736f225d706bc1827af283501/ide/dlight.nativeexecution/src/org/netbeans/modules/nativeexecution/support/hostinfo/impl/UnixHostInfoProvider.java#L69

**Comment by tmulle** [comment]
Hi again... just wanted to let you know that this is still missing in NetBeans 14. I had to copy my hosting and the ARM folder for Mac to the installation.

Wasn't sure if this was included in the official releases yet.

**Comment by oyarzun** [comment]
@tmulle correct no changes have been incorporated into an official release or master.

**Comment by tmulle** [comment]
I just installed NetBeans 16 and looks like the changes still aren't in for the terminal.
I have to copy my modified `hostinfo.sh` and ARM folder I locally built.

Will this be in a future release? I know not everyone has M1 Macs.. 

I think there are companies you can rent M1 Macs in the cloud for build processes for those that don't or can't have the proper machines.

**Comment by tmulle** [comment]
Hi, any status on this? I just installed Netbeans 17 (working great so far!) - Although not a fan of the new MacOS icons. I don't like the outline folders...:(

Anyway, in order to get my terminal to open in Netbeans I had to copy the files once again.

Will this be going into master anytime soon?

**Comment by ctipper** [comment]
I am unable to tell what the blocker is on this thread, Jan 2022 this PR was raised, any status update? Netbeans Terminal not functional on Apple Silicon is not a minority problem anymore.

**Comment by tmulle** [comment]
@ctipper @neilcsmith-net 
If it helps I can submit the binaries that I built a while back that I keep copying from new release of NB..it consists of the binaries for the libs and the modify `hostinfo.sh` file.

I see #6012 was just posted so other people are now hitting this issue so it's now more important I would think.

It would be nice to not have to keep copying my binaries to get the terminal working in NB.

I just had to do it for NB 18.

**Comment by ctipper** [comment]
I now have an M2 Mac and I'm curious why I was able to install Netbeans 18 with aarch64 JDK 17 _and_ have a working Terminal, I think it's running in Rosetta, I had a new installation.

**Comment by fixbugbroken** [comment]
I can confirm similar behavior using the Netbeans 18 zip archive with M2 Mac. The terminal is blank and does not show any prompts. I'm using the zip archive since it runs as a native app (kind=apple under activity monitor with no prompts for Rosetta) where as the package installer does not. 

However, I am getting the following error message when while launching the zip archive version of Netbeans:

<img width="372" alt="Screenshot 2023-06-18 at 7 33 10 PM" src="https://github.com/apache/netbeans/assets/98848435/0ba6e400-8a62-42d0-907e-65fa34124d86">

This appears twice before the Netbeans window opens. Note this has been reported here https://github.com/apache/netbeans/issues/6014

**Comment by ctipper** [comment]
So if you use package installer and have aarch64 JDK in `/Library/Java/VirtualMachines` Netbeans does execute natively. It is only the Terminal that runs in Rosetta. All my experience is that trying to execute netbeans without the launcher runtime i.e. from the bundled script, fools all the logic that triggers `tccutil` and may mess up the logic Apple uses to trigger Rosetta.
<img width="926" alt="Screenshot 2023-06-19 at 14 07 13" src="https://github.com/apache/netbeans/assets/959564/35af6cc5-2b59-4992-b527-f85bc5c947f2">

**Comment by fixbugbroken** [comment]
@ctipper thanks for info.

I'm trying to keep Rosetta of my dev machine so that I get immediate warnings from macOS if our universal app bundle for macOS fails to be recognized as a universal app. We have had issues with Info.plist settings and launcher scripts that trigger Rosetta (even though the project is built to be universal). This allows us to catch these kind of issues early and easily.

**Comment by neilcsmith-net** [comment]
@fixbugbroken I assume that you tried the suggested workaround for the error message on libjnidispatch?  I guess this might be because loading an unsigned jnilib will fail except in Rosetta?  That might rule out the zip package for macOS M1/M2 for good?!

I'm happy to look at building a variant of the Codelerity installer with an aarch64 JDK and/or no JDK, if you'd be interested in testing?  Contact me via email on GitHub profile.  I'm not sure if there's any universal JDK yet?

**Comment by fixbugbroken** [comment]
@neilcsmith-net Yes clearing the extended attribute removes the warning from macOS. However, as mentioned by the OP the zip file does not contain a directory for MacOSX-aarch64 binaries under bin/nativeexecution directory.

I could certainly test a Codelerity installer if that will help Netbeans build an installer that does not prompt for Rosetta. I will reach out to you via e-mail.

There are arm64 builds for all JDK versions as far back as JDK 8 (see OpenJDK, Adoptium and Azul). I'm currently running an arm64 distribution of JDK 20 with the Netbeans zip package. Of course the arm64 JDK distributions do not trigger prompts for Rosetta.

**Comment by neilcsmith-net** [comment]
@fixbugbroken take a look at the installer linked from https://github.com/apache/netbeans/issues/6052#issuecomment-1615801376

The `nativeexecution` directory that initiated this issue is a slightly separate concern that will still need addressing.

> There are arm64 builds for all JDK versions as far back as JDK 8 (see OpenJDK, Adoptium and Azul). I'm currently running an arm64 distribution of JDK 20 with the Netbeans zip package. Of course the arm64 JDK distributions do not trigger prompts for Rosetta.

That wasn't what I meant by universal JDK though.  I'm aware of the arm64 JDKs.  We (as in Codelerity) might ship a separate installer with an arm64 JDK bundled, although I'd rather see this issue resolved first.  The Apache release will never bundle a JDK.

The other thing is considering using NBPackage to build the Apache released macOS installer as well, with a universal build of the Swift launcher, as well as fixing the signing issues.  That's being discussed in the other issue.

**Comment by ctipper** [comment]
I tried Netbeans 19 the work around has no effect now and this PR is more urgent than ever. Not a particular fan of the new pkg installer, it's only meant for distributing libraries and it prevents the work around I mentioned above.

**Comment by neilcsmith-net** [comment]
> Not a particular fan of the new pkg installer, it's only meant for distributing libraries and it prevents the work around I mentioned above.

I'm not sure what you mean by the "only meant for distributing libraries" comment?  Using `pkg`?  The old installer was the same, just broken in multiple other ways.

We might look at shipping the app bundle directly in a dmg or zip (easier and preferred in my opinion).  I doubt this will make a difference for you - everything is now signed with the hardened runtime and the launcher is universal architecture when no JDK is specified.  So, altering files in the bundle is not possible, and the fact that the launcher architecture might have fooled macOS in some circumstances was a happy accident.

You could use nbpackage to build from the zip yourself, forcing the launcher to x86_64 rather than universal, or just look at one of various macOS options to force use of Rosetta for the launcher?  That might still work.

Simply put, we need to fix this properly by finding a way to work with the correct architecture, ideally by NB20.

**Comment by ctipper** [comment]
So I think not triggering Rosetta is governed by how app is installed. DMG method before and I think it should be brought back, helps installing side by side.

**Comment by ctipper** [comment]
I think I'll stick to Netbeans 18, I really have no clue why this issue has been open for the years.

**Comment by neilcsmith-net** [comment]
The previous installer was still a `pkg`, just inside a `dmg`!  It has nothing to do with the change in the triggering of Rosetta.  That is because the Swift launcher in NB18 was built with `x86_64` and the one in NB19 is built with universal architecture.

**Comment by ctipper** [comment]
I didn't see that that would explain it.

**Comment by ctipper** [comment]
Also an unnecessary change, and it stopped the terminal from working.

**Comment by neilcsmith-net** [comment]
> Also an unnecessary change, and it stopped the terminal from working.

The changes were a necessary part of fixing #6052 and other related issues.

NetBeans does not yet fully support running on macOS Arm unfortunately.  You can run on an `x86_64` JDK and use `arm64` JDKs for projects.

Personally, I'd prefer we stopped shipping a macOS installer without bundled JDK runtime anyway - using the zip in those circumstances is preferable IMO for a multitude of reasons.

**Comment by neilcsmith-net** [comment]
@tmulle what we probably need to do is extricate the existing source to a separate repo (similar to https://github.com/apache/netbeans-native-launchers ) then look at using GitHub actions to build them, and run a release vote on them.  The NetBeans build can then use the released native binaries.

I think your input into that would be very welcomed!  I also have a local M1 mac, so happy to do some testing and helping out with this.

cc/ @ebarboni for input

**Comment by sroeper** [comment]
The problem still exists on Apple Silicon with NB19.

**Comment by neilcsmith-net** [comment]
@sroeper of course it's open source - the source is at https://github.com/apache/netbeans/tree/master/ide/dlight.nativeexecution/tools

If we can get a PR in that includes the relevant changes (eg. @oyarzun or @tmulle changes linked above??) then we can look at a similar workflow as for the profiler to release the binaries for consumption in the build.  I for one would like to see this fixed in NB20.  There is a lot that "simple contributors" can help out with here.

**Comment by tmulle** [comment]
@neilcsmith-net 

I can submit a PR for the changes I did, but it is just a few lines added to `hostinfo.sh`.

As far as any other changes I did, I didn't do anything else but following the instructions at https://github.com/apache/netbeans/issues/3467#issuecomment-1015056935

To test building on my M1.

If you follow the comments from that link down you can see what I ran into.

TL;DR - running `buildall.sh` builds the code on my M1 mac to `netbeans/ide/dlight.nativeexecution/tools/MacOSX-arm` when the final directory needs to be `MacOSX-arm_64` as mentioned in the comments above.

**Comment by neilcsmith-net** [comment]
Thanks @vieiro but I wasn't intending to use OSUOSL or user compiled binaries (which would both be -1 anyway).  We already have access to macOS cross-compilation and/or Apple Silicon via GitHub Actions.  As long as the build process in the main repo works, I intend to fork the workflow I've just merged for the profiler binaries and release via dist.a.o - which is close to your second suggestion.  

See #6502  I'd like to see if we can fix both these for NB20.

As well as merging required fixes, we need to clarify exactly which folders are required (ie. anything outside of `dlight.nativeexecution/tools`).  We might need the same hack as currently in the profiler source bundle to replicate the destination folders?

Both Apple and GitHub are already [ASF sponsors](https://www.apache.org/foundation/sponsors) btw! :smile:

**Comment by neilcsmith-net** [comment]
... actually, I may have jumped the gun on availability of the architecture on GitHub actions.  Had seen a reference to being in public beta.  Need to check, or we're looking at needing to adapt these builds to support universal architecture, or worst case for now, I'll compile locally from a generated voting source bundle.

**Comment by sroeper** [comment]
@neilcsmith-net Yes, it's enough to have a x86_64 runner and cross compile the binaries. There is no need for a M1/M2/Mwhatever.

The only change you have to do is to call clang with the -arch option.
For x86_64 call with -arch x86_64
For arm64 call with -arch arm64

To build something which includes both (i.e. universal library/executable) call with -arch  x86_64 -arch arm64

Works the same on a M1/M2

**Comment by neilcsmith-net** [comment]
I've adapted the workflows of @tmulle and @oyarzun for #6513 - thanks both! Artefacts from the workflow can be found at eg. https://github.com/apache/netbeans/actions/runs/6382908341 ... or look for a later run.

If anyone is willing to check those, that would be great!  There's still some work to do on that, but it might be enough to get us some terminal support for Apple Silicon in NB20?!

**Comment by neilcsmith-net** [comment]
Should be working in NB20. A release candidate should be available next week. Please help testing that when it's ready.
