### ISSUE TITLE
NoSuchFieldError: SNIPPET in JavadocCompletionUtils

### ISSUE THREAD

**Issue by johnmanko** [apache/netbeans#4867]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Auto-completion and hot-linking stopped working.

```
java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: SNIPPET [in thread "AWT-EventQueue-0"]
	at org.netbeans.modules.java.editor.base.javadoc.JavadocCompletionUtils.<clinit>(JavadocCompletionUtils.java:350)
	at org.netbeans.modules.java.editor.base.javadoc.JavadocImports.isInsideReference(JavadocImports.java:643)
	at org.netbeans.modules.editor.java.GoToSupport$6.run(GoToSupport.java:659)
	at org.netbeans.editor.BaseDocument.render(BaseDocument.java:1402)
	at org.netbeans.modules.editor.java.GoToSupport.getIdentifierOrLambdaArrowSpan(GoToSupport.java:639)
	at org.netbeans.modules.java.editor.hyperlink.JavaHyperlinkProvider.getHyperlinkSpan(JavaHyperlinkProvider.java:63)
	at org.netbeans.modules.java.editor.hyperlink.JavaHyperlinkProvider.isHyperlinkPoint(JavaHyperlinkProvider.java:58)
	at org.netbeans.modules.java.openjdk.editor.JavaToCHyperlinkProvider.isHyperlinkPoint(JavaToCHyperlinkProvider.java:72)
	at org.netbeans.lib.editor.hyperlink.HyperlinkOperation.findProvider(HyperlinkOperation.java:266)
	at org.netbeans.lib.editor.hyperlink.HyperlinkOperation.performHyperlinking(HyperlinkOperation.java:224)
	at org.netbeans.lib.editor.hyperlink.HyperlinkOperation.mouseMoved(HyperlinkOperation.java:200)
	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:338)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6661)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3416)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4991)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4588)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
Caused: java.lang.NoClassDefFoundError: Could not initialize class org.netbeans.modules.java.editor.base.javadoc.JavadocCompletionUtils
	at org.netbeans.modules.java.editor.javadoc.JavadocCompletionProvider.getAutoQueryTypes(JavadocCompletionProvider.java:51)
	at org.netbeans.modules.editor.completion.CompletionImpl.insertUpdate(CompletionImpl.java:327)
	at org.netbeans.lib.editor.util.swing.PriorityDocumentListenerList.insertUpdate(PriorityDocumentListenerList.java:60)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:227)
	at org.netbeans.editor.BaseDocument.fireInsertUpdate(BaseDocument.java:1647)
	at org.netbeans.editor.BaseDocument.handleInsertString(BaseDocument.java:822)
	at org.netbeans.editor.BaseDocument$FilterBypassImpl.insertString(BaseDocument.java:2643)
	at java.desktop/javax.swing.text.DocumentFilter.insertString(DocumentFilter.java:105)
	at org.openide.text.CloneableEditorSupport$DocFilter.insertString(CloneableEditorSupport.java:2340)
	at org.netbeans.editor.BaseDocument.insertString(BaseDocument.java:741)
	at org.netbeans.editor.BaseKit$DefaultKeyTypedAction.insertString(BaseKit.java:1324)
	at org.netbeans.editor.BaseKit$DefaultKeyTypedAction.performTextInsertion(BaseKit.java:1397)
	at org.netbeans.editor.BaseKit$DefaultKeyTypedAction.access$100(BaseKit.java:1052)
	at org.netbeans.editor.BaseKit$DefaultKeyTypedAction$3.run(BaseKit.java:1256)
	at org.netbeans.editor.GuardedDocument.runAtomicAsUser(GuardedDocument.java:333)
	at org.netbeans.editor.BaseKit$DefaultKeyTypedAction.actionPerformed(BaseKit.java:1231)
	at org.netbeans.editor.ext.ExtKit$ExtDefaultKeyTypedAction.actionPerformed(ExtKit.java:1055)
	at org.netbeans.editor.BaseAction.actionPerformed(BaseAction.java:322)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2956)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:3004)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2918)
	at java.desktop/java.awt.Component.processEvent(Component.java:6393)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4991)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1146)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

### How to reproduce

Not sure how to reproduce.

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Ubuntu 22.04.1 LTS

### JDK

OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-222.04)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
`DocTree.Kind.SNIPPET` should exist in both, your JDK and in nb-javac of NetBeans 15. I am not sure what is happening there. Did you import modules from an old NB config or something similar?

**Comment by johnmanko** [comment]
@mbien I'm sure I did import a module from a previous installation.  Only Darcula LAF for NetBeans 1.6 is listed under User Installed Plugins.  I disabled that plugin and I'm still having problems.  I should also note, I noticed another error upon IDE startup:

```
java.lang.NullPointerException: Cannot invoke "org.netbeans.api.java.source.JavaSource.runUserActionTask(org.netbeans.api.java.source.Task, boolean)" because "newJavaSource" is null
	at org.netbeans.modules.j2ee.metadata.model.api.support.annotation.AnnotationModelHelper.runJavaSourceTask(AnnotationModelHelper.java:156)
	at org.netbeans.modules.j2ee.metadata.model.api.support.annotation.AnnotationModelHelper.runJavaSourceTask(AnnotationModelHelper.java:124)
	at org.netbeans.modules.websvc.rest.model.impl.RestServicesMetadataModelImpl.runReadAction(RestServicesMetadataModelImpl.java:52)
	at org.netbeans.modules.websvc.rest.nodes.RestServicesNodeFactory$RestNodeList$1.run(RestServicesNodeFactory.java:86)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

```
Here are all of my active plugins.

![image](https://user-images.githubusercontent.com/3154748/198332220-650912cd-ba0f-49a0-8705-42f49a9b12ff.png)
![image](https://user-images.githubusercontent.com/3154748/198332301-60c2c13e-9c72-43da-80e6-e10e873354cf.png)
![image](https://user-images.githubusercontent.com/3154748/198332392-2bba5fed-6343-48a7-aaaf-638b4c700122.png)
![image](https://user-images.githubusercontent.com/3154748/198332460-3adcf9ca-7186-4527-995f-3210b2de3b3e.png)
![image](https://user-images.githubusercontent.com/3154748/198332550-4838b03d-182b-4518-ac4d-defa7943de6d.png)

I'll try to disabled what I can.

**Comment by mbien** [comment]
I see. So what is likely happening here is #4838. Could you try to rename your NetBeans config and start with a fresh one. If this fixes it we know that it was a plugin import.

your config on ubuntu should be at `[home]/.netbeans/[nb_version]` by default. (don't import anything what has `javac` in the name)

good news is that this is fixed in NB 16 (hopefully).

**Comment by johnmanko** [comment]
@mbien 

I disabled the following plugins and now everything works.  Hopefully this helps.

* Bugzilla
* Mercurial
* AngularJS Editor
* DukeScript Gradle Project Wizard
* Gradle Projects Distributions
* Gradle
* Gradle Java EE
* Typescript Editor

**Comment by mbien** [comment]
yeah maybe its time for a reset. Start NB 16 once its out with a fresh config and then incrementally add plugins again :)

**Comment by johnmanko** [comment]
Sounds good. Thanks.

**Comment by johnmanko** [comment]
Ugh, it's back, even with those plugin disabled. I went through and disable more plugin, and it keep coming back.  I cleared all netbeans cache, still an issue.  It's to the point I can't open projects.  So frustrating.  What's the ETA on NB16?  I can't work at this point, and I'm going to have to IntelliJ.

**Comment by neilcsmith-net** [comment]
@johnmanko officially released - zip at https://dlcdn.apache.org/netbeans/netbeans/16/ , but the Apache installers are still inbound.  Community installers are up already - follow the link on https://netbeans.apache.org/download/nb15/ and you'll find NetBeans 16!

**Comment by johnmanko** [comment]
Here is the log from Netbeans.  

[netbeans-messages.log](https://github.com/apache/netbeans/files/10134989/netbeans-messages.log)

**Comment by johnmanko** [comment]
@neilcsmith-net Thank you.  I'm giving that a try now.

**Comment by johnmanko** [comment]
This is no longer an issue for Netbeans 16.  Not sure if you want to close it or keep it open.  Will you be providing additional update to v15?

**Comment by mbien** [comment]
> This is no longer an issue for Netbeans 16. Not sure if you want to close it or keep it open. Will you be providing additional update to v15?

NetBeans releases replace each other when a new one is released. There are no LTS versions anymore. It is recommended to update to the current version.
