### ISSUE TITLE
New JFrame code is garbled

### ISSUE THREAD

**Issue by rdbramble** [apache/netbeans#6861]
### Apache NetBeans version

Apache NetBeans 19

### What happened

New JFrame form command results in a form with code that's garbled. Partial example follows:

```java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
ackage

inf;

/**
 *
 * @author danie
 */
public class NewJFrame extends javax.swing.JFrame

/**
 *
 *     * Creates new form New
 * Frame
 */

public
    ewJFrame()
    {
        initComponents();
     *     }


```

### How to reproduce

select package right mouse click -> New -> JFrame Form. The resulting code cannot be compiled as is. I even downloaded NetBeans v20 and the behavior is there too. I don't do this very often but the last time I did it worked fine I'm thinking that was at least a couple versions ago.

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; en_US (nb)

### JDK

15.0.2; Java HotSpot(TM) 64-Bit Server VM 15.0.2+7-27

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I'm able to reproduce this issue.

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
I can't reproduce this problem.

what project type is this? Did you import your NB 19 config into NB 20?

> 15.0.2; Java HotSpot(TM) 64-Bit Server VM 15.0.2+7-27

btw JDK 15 is end of life, the supported versions of NB 20 would be 11, 17 and 21 which are all LTS releases (JDK 15 was no LTS release).

**Comment by mbien** [comment]
do you have this file in your netbeans config: `config/Templates/GUIForms/JFrame.java`, if it exists, is the content garbled?

`Help-> About` will show you where the config is located, it is the "User directory" property.

**Comment by mbien** [comment]
@rdbramble can you use the githup UI to reply, the email reply does not work properly, e.g there is no screenshot.

having no templates in your user config would be ok, this would only indicate that you haven't modified the default templates (I suspected the modified template might be broken). However, having no templates in the template window would indicate a problem.

**Comment by rdbramble** [comment]
From: rdanielbramblett@gmail.com <rdanielbramblett@gmail.com> 
Sent: Monday, December 18, 2023 07:36
To: 'apache/netbeans' <reply+A3EGUK44FZHLYXILGBOD7CGDRVSHBEVBNHHHT2HQ7Y@reply.github.com>; 'apache/netbeans' <netbeans@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [apache/netbeans] New JFrame code is garbled (Issue #6861)

Thank you for responding.

I seem to be missing the Templates. No idea how that might have happened.

Opened the User Directory -> config and no Templates. See screenshot. How do I recover?

![screenshot](https://github.com/apache/netbeans/assets/113797675/7d0b34f3-eb91-484e-bb02-d319da0c0378)

**Comment by rdbramble** [comment]
GitHub updated.

**Comment by rdbramble** [comment]
Done

**Comment by mbien** [comment]
I cleaned up the email replies. github's email reply integration is unfortunately barely useable and there is no way for us to turn it off. Please use the web version of the issue for replies in future, thanks.

> Opened the User Directory -> config and no Templates. See screenshot. How do I recover?

this screenshot is still missing.

Can you try again to create a new JFrame Form and then attach the `messages.log`? You can simply drag and drop the file into the comment window on github..

**Comment by rdbramble** [comment]
Well it's a bit embarrassing but when I created a new JFrame just now it went off without a hitch. Code came out fine. I'm perplexed by this result b/c when I opened the case I could recreate the problem consistently. The only difference between now and then is I've rebooted my machine a few times. Never the less here's the log files from today and the historical one from 17 Dec. (messages 17 Dec.log)
[messages.log](https://github.com/apache/netbeans/files/13728659/messages.log)
[messages 17 Dec.log](https://github.com/apache/netbeans/files/13728673/messages.17.Dec.log)

Perhaps something in there will solve the mystery. But at this point other than satisfying curiosity I'm not sure anything else is required because I can't recreate the problem now.

**Comment by mbien** [comment]
this is suspicious. NB doesn't have `met.foundation.notification.Notification` in the repo, this must be from a plugin or something like that. Both logs had many of the following exceptions:

```
INFO: met/foundation/notification/Notification
java.lang.ClassNotFoundException: met.foundation.notification.Notification
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at org.netbeans.api.java.classpath.ClassLoaderSupport.findClass(ClassLoaderSupport.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused: java.lang.NoClassDefFoundError: met/foundation/notification/Notification
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3325)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3350)
	at java.base/java.lang.Class.getMethods(Class.java:1996)
	at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:70)
	at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:71)
	at java.desktop/java.beans.Introspector.getTargetMethodInfo(Introspector.java:1027)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:443)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:195)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:281)
	at java.desktop/java.beans.Introspector.<init>(Introspector.java:424)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:195)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:281)
	at java.desktop/java.beans.Introspector.<init>(Introspector.java:424)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:195)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:281)
	at java.desktop/java.beans.Introspector.<init>(Introspector.java:424)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:195)
	at org.openide.util.Utilities.getBeanInfo(Utilities.java:314)
[catch] at org.netbeans.modules.form.FormUtils.getBeanInfo(FormUtils.java:1907)
	at org.netbeans.modules.form.palette.PaletteItem.getBeanDescriptor(PaletteItem.java:349)
	at org.netbeans.modules.form.palette.PaletteItem.getDisplayName(PaletteItem.java:259)
	at org.netbeans.modules.form.palette.PaletteItemDataObject$ItemNode.getDisplayName(PaletteItemDataObject.java:308)
	at org.openide.nodes.FilterNode.getDisplayName(FilterNode.java:503)
	at org.openide.nodes.FilterNode.getDisplayName(FilterNode.java:503)
	at org.netbeans.modules.form.palette.PaletteUtils$1.run(PaletteUtils.java:224)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

**Comment by rdbramble** [comment]
Yep I saw that too. Recompiled the module just now and the issue isn't in the log any longer. I'll keep an eye out for it. Odd, I didn't get a dependency error on compile of the main app.
