### ISSUE TITLE
sourcefile links in output not ckickable/not open linked source

### ISSUE THREAD

**Issue by sebastian-toepfer** [apache/netbeans#7493]
### Apache NetBeans version

Apache NetBeans 22

### What happened

Execute a Junit test. In the output, Netbeans (Maven) will show the stacktraces of the failed test. But it is not possible to go to the linked position.
I don't want you to have to fix the problem. I need a guide to find the right place so I can try to fix it myself.

### Language / Project Type / NetBeans Component

Java Maven Projekt / Output (unsure)

### How to reproduce

- write a test which will faild
- execute the test
- open the output
- kick a link in the stacktrace

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux

### JDK

17 und 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

always 

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
hi @sebastian-toepfer, this might be already fixed via https://github.com/apache/netbeans/pull/7391

could you try a nightly build and check if it is working? https://github.com/apache/netbeans?tab=readme-ov-file#download

**Comment by sebastian-toepfer** [comment]
In
```
Product Version: Apache NetBeans IDE DEV (Build dev-28211847bffbc363528fdcb5e47d7b6152e00a2c)
Java: 21.0.3; OpenJDK 64-Bit Server VM 21.0.3+9-LTS
Runtime: OpenJDK Runtime Environment 21.0.3+9-LTS
System: Linux version 6.1.0-21-amd64 running on amd64; UTF-8; en_US (nb)
```
it is still in unit test which runs in a normal `clean build`

**Comment by sebastian-toepfer** [comment]
If I understand the fix correctly, it's to fix how Netbeans determines Java files in a stacktrace, but my stacktrace looks fine. i'm just not able to navigate to the posion by clicking on it.

![image](https://github.com/apache/netbeans/assets/61313468/64e4901b-bb0d-4744-b300-85b83f4d1625)

**Comment by sebastian-toepfer** [comment]
no longer reproducible with nb23. sometimes it still happens, but no longer every time
